packages:
  - "apps/*"
  - "packages/*"

catalogs:
  default:
    # Build tools
    prettier: "^3.6.2"
    turbo: "^2.5.6"
    typescript: "^5.9.2"
    vite: "^7.1.2"

    # React
    react: "^19.1.1"
    react-dom: "^19.1.1"

    # Next.js
    next: "^15.4.5"
    "@next/eslint-plugin-next": "^15.4.5"

    # Types
    "@types/node": "^20.19.9"
    "@types/react": "^19.1.10"
    "@types/react-dom": "^19.1.7"

    # ESLint
    eslint: "^9.32.0"
    "@eslint/js": "^9.32.0"
    "@typescript-eslint/eslint-plugin": "^8.39.0"
    "@typescript-eslint/parser": "^8.39.0"
    "eslint-config-prettier": "^9.1.2"
    "eslint-plugin-only-warn": "^1.1.0"
    "eslint-plugin-react": "^7.37.5"
    "eslint-plugin-react-hooks": "^5.2.0"
    "eslint-plugin-react-refresh": "^0.4.20"
    "eslint-plugin-turbo": "^2.5.5"
    "typescript-eslint": "^8.39.0"

    # UI Libraries
    "lucide-react": "^0.475.0"
    "next-themes": "^0.4.6"
    "@radix-ui/react-slot": "^1.2.3"
    "@radix-ui/react-dialog": "^1.1.15"
    "@radix-ui/react-separator": "^1.1.7"
    "@radix-ui/react-tooltip": "^1.2.8"
    "class-variance-authority": "^0.7.1"
    "clsx": "^2.1.1"
    "tailwind-merge": "^3.3.1"
    "tw-animate-css": "^1.3.6"
    "zod": "^3.25.76"

    # Tailwind
    tailwindcss: "^4.1.11"
    "@tailwindcss/postcss": "^4.1.11"

    # Testing
    vitest: "^3.2.4"
    "@vitest/browser": "^3.2.4"
    "@vitest/coverage-v8": "^3.2.4"
    playwright: "^1.55.0"

    # Storybook
    storybook: "^9.1.8"
    "@chromatic-com/storybook": "^4.1.1"
    "@storybook/addon-a11y": "^9.1.8"
    "@storybook/addon-docs": "^9.1.8"
    "@storybook/addon-onboarding": "^9.1.8"
    "@storybook/addon-vitest": "^9.1.8"
    "@storybook/nextjs": "^9.1.8"
    "@storybook/nextjs-vite": "^9.1.8"
    "@storybook/react-vite": "^9.1.8"
    "eslint-plugin-storybook": "^9.1.8"

    # Database
    prisma: "^6.16.3"
    "@prisma/client": "^6.16.3"
    tsx: "^4.19.2"

    # Other tools
    globals: "^15.15.0"
    "@vitejs/plugin-react": "^5.0.0"
    "@turbo/gen": "^2.5.5"
